/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#000f5d',
        'secondary-fixed-dim': '#bbc3ff',
        'inverse-primary': '#2848ee',
        'tertiary-fixed-dim': '#ffb599',
        'on-tertiary-container': '#ffeee8',
        'outline-variant': '#444656',
        'inverse-surface': '#e5e2e1',
        'surface-container-high': '#2a2a2a',
        'on-background': '#e5e2e1',
        'on-primary': '#001d93',
        background: '#131313',
        'on-tertiary': '#5a1c00',
        secondary: '#bbc3ff',
        error: '#ffb4ab',
        'on-error-container': '#ffdad6',
        'primary-container': '#3d5afe',
        'primary-fixed': '#dee0ff',
        'on-primary-container': '#f1f0ff',
        'on-primary-fixed-variant': '#002ccd',
        'inverse-on-surface': '#313030',
        'surface-dim': '#131313',
        'surface-container-low': '#1c1b1b',
        primary: '#bbc3ff',
        'error-container': '#93000a',
        'primary-fixed-dim': '#bbc3ff',
        outline: '#8e8fa2',
        'secondary-fixed': '#dee0ff',
        surface: '#131313',
        'on-error': '#690005',
        'surface-variant': '#353534',
        'on-tertiary-fixed-variant': '#7f2b00',
        'on-secondary-container': '#a9b4ff',
        'on-tertiary-fixed': '#370e00',
        'on-surface-variant': '#c5c5d9',
        'on-secondary': '#1c2971',
        'on-secondary-fixed-variant': '#344088',
        'surface-container': '#201f1f',
        'on-surface': '#e5e2e1',
        'tertiary-container': '#c04500',
        'surface-tint': '#bbc3ff',
        tertiary: '#ffb599',
        'secondary-container': '#37438b',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'tertiary-fixed': '#ffdbce',
        'surface-container-highest': '#353534',
        'on-secondary-fixed': '#010f5c',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
